export const GET_SCIENCE_QUESTIONS = 'GET_SCIENCE_QUESTIONS'
export const GET_SCIENCE_QUESTIONS_SUCCESS = 'GET_SCIENCE_QUESTIONS_SUCCESS'
export const GET_SCIENCE_QUESTIONS_ERROR = 'GET_SCIENCE_QUESTIONS_ERROR'
